In [1]:
# Import the required libraries.

import pandas as pd
import numpy as np

In [ ]:
# Load all project datasets.

shipments = pd.read_csv("../Dataset/shipments.csv")
customers = pd.read_csv("../Dataset/customers.csv")
carriers = pd.read_csv("../Dataset/carriers.csv")
ports = pd.read_csv("../Dataset/ports.csv")

In [10]:
# Display the first 5 records of each dataset.

shipments.head()

,movement_id,shipment_id,container_id,customer_id,carrier_name,origin_port,origin_city,origin_country,destination_port,destination_city,...,container_type,cargo_type,shipment_value_usd,temperature_celsius,humidity_percent,delay_duration_hours,delay_penalty_rate_usd_per_hr,total_delay_penalty_usd,is_damaged,late_arrival_flag
0,MVT300001,SHP400000,CNT200001,CUST0079,Maersk,Port of Los Angeles,Los Angeles,US,Port of Dubai (Jebel Ali),Dubai,...,Reefer,Frozen Food,47709.85,-23.0,81.71,25.25,19.83,500.82,False,True
1,MVT300002,SHP400000,CNT200001,CUST0079,Maersk,Port of Los Angeles,Los Angeles,US,Port of Dubai (Jebel Ali),Dubai,...,Reefer,Frozen Food,58166.39,-23.0,81.71,13.70,22.78,312.09,False,True
2,MVT300004,SHP400000,CNT200001,CUST0079,Maersk,Port of Los Angeles,Los Angeles,US,Port of Dubai (Jebel Ali),Dubai,...,Reefer,Frozen Food,86482.24,-23.0,81.71,40.70,20.93,851.94,False,True
3,MVT300006,SHP400000,CNT200001,CUST0079,Maersk,Port of Los Angeles,Los Angeles,US,Port of Dubai (Jebel Ali),Dubai,...,Reefer,Frozen Food,88148.54,-23.0,81.71,20.85,21.17,441.44,False,True
4,MVT300007,SHP400000,CNT200001,CUST0079,Maersk,Port of Los Angeles,Los Angeles,US,Port of Dubai (Jebel Ali),Dubai,...,Reefer,Frozen Food,41482.11,-23.0,81.71,39.04,22.90,893.92,False,True

In [11]:
customers.head()

,customer_id,company_name,country,phone,email,registration_year,credit_tier
0,CUST0001,GreenPath Exports,DE,+4-859-5614226,greenpathexp@yahoo.com,2011,Silver
1,CUST0002,SilkRoute Trading,DE,+87-858-2458591,silkroutetra@trade.org,2014,Gold
2,CUST0003,PacificRim Logistics,US,+12-323-4903402,pacificrimlo@trade.org,2017,Gold
3,CUST0004,AtlanticCargo Co,GB,+26-833-8038374,atlanticcarg@yahoo.com,2015,Bronze
4,CUST0005,Nordic Trade Ltd,US,+98-925-3678638,nordictradel@biz.com,2014,Bronze

In [12]:
carriers.head()

,Carrier ID,Carrier Name,HQ Country,Country Code,Founded Year,Fleet Size,Max TEU Capacity,Credit Rating,Contact Email,Avg Rating (1-5),Status
0,CAR001,Maersk,Denmark,DK,1904,700,150000,AAA,contact@maersk.com,4.7,Active
1,CAR002,MSC,Switzerland,CH,1970,580,130000,AA+,contact@msc.com,4.5,Active
2,CAR003,CMA CGM,France,FR,1978,500,112000,AA,contact@cmacgm.com,4.4,Active
3,CAR004,Hapag-Lloyd,Germany,DE,1847,250,81000,AA-,contact@hapag-lloyd.com,4.6,Active
4,CAR005,Evergreen,Taiwan,TW,1968,200,68000,A+,contact@evergreen.com,4.3,Active

In [13]:
ports.head()

,port_id,port_name,city,country_code,country_full,port_type,annual_capacity_teu
0,PORT001,Port of Los Angeles,Los Angeles,US,United States,Container,"9,337,000"
1,PORT002,Port of Rotterdam,Rotterdam,NL,Netherlands,Container/Bulk,"14,791,000"
2,PORT003,Port of Dubai (Jebel Ali),Dubai,AE,United Arab Emirates,Container,"13,627,000"
3,PORT004,Port of Hamburg,Hamburg,DE,Germany,Container,"8,731,000"
4,PORT005,Port of Shanghai (Yangshan),Shanghai,CN,China,Container,"47,030,000"

In [15]:
# Display the column names of each dataset.

shipments.columns

Index(['movement_id', 'shipment_id', 'container_id', 'customer_id',
       'carrier_name', 'origin_port', 'origin_city', 'origin_country',
       'destination_port', 'destination_city', 'destination_country',
       'departure_timestamp', 'expected_arrival_timestamp',
       'actual_arrival_timestamp', 'transit_duration_hours', 'status',
       'container_type', 'cargo_type', 'shipment_value_usd',
       'temperature_celsius', 'humidity_percent', 'delay_duration_hours',
       'delay_penalty_rate_usd_per_hr', 'total_delay_penalty_usd',
       'is_damaged', 'late_arrival_flag'],
      dtype='str')

In [16]:
customers.columns

Index(['customer_id', 'company_name', 'country', 'phone', 'email',
       'registration_year', 'credit_tier'],
      dtype='str')

In [17]:
carriers.columns

Index(['Carrier ID', 'Carrier Name', 'HQ Country', 'Country Code',
       'Founded Year', 'Fleet Size', 'Max TEU Capacity', 'Credit Rating',
       'Contact Email', 'Avg Rating (1-5)', 'Status'],
      dtype='str')

In [18]:
ports.columns

Index(['port_id', 'port_name', 'city', 'country_code', 'country_full',
       'port_type', 'annual_capacity_teu'],
      dtype='str')

In [19]:
# Display information about each dataset.

shipments.info()

<class 'pandas.DataFrame'>
RangeIndex: 358990 entries, 0 to 358989
Data columns (total 26 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   movement_id                    358990 non-null  str
 1   shipment_id                    358990 non-null  str
 2   container_id                   358990 non-null  str
 3   customer_id                    358990 non-null  str
 4   carrier_name                   358990 non-null  str
 5   origin_port                    358990 non-null  str
 6   origin_city                    358990 non-null  str
 7   origin_country                 358990 non-null  str
 8   destination_port               358990 non-null  str
 9   destination_city               358990 non-null  str
 10  destination_country            358990 non-null  str
 11  departure_timestamp            358990 non-null  str
 12  expected_arrival_timestamp     358990 non-null  str
 13  actual_arrival_timestamp       117694 non-null  str
 14  transit_duration_hours         358990 non-null  float64
 15  status                         358990 non-null  str
 16  container_type                 358990 non-null  str
 17  cargo_type                     358990 non-null  str
 18  shipment_value_usd             358990 non-null  float64
 19  temperature_celsius            358990 non-null  float64
 20  humidity_percent               358990 non-null  float64
 21  delay_duration_hours           358990 non-null  float64
 22  delay_penalty_rate_usd_per_hr  358990 non-null  float64
 23  total_delay_penalty_usd        358990 non-null  float64
 24  is_damaged                     358990 non-null  bool
 25  late_arrival_flag              358990 non-null  bool
dtypes: bool(2), float64(7), str(17)
memory usage: 124.0 MB

In [20]:
customers.info()

<class 'pandas.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   customer_id        300 non-null    str
 1   company_name       300 non-null    str
 2   country            300 non-null    str
 3   phone              300 non-null    str
 4   email              300 non-null    str
 5   registration_year  300 non-null    int64
 6   credit_tier        300 non-null    str
dtypes: int64(1), str(6)
memory usage: 37.8 KB

In [21]:
carriers.info()

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Carrier ID        6 non-null      str
 1   Carrier Name      6 non-null      str
 2   HQ Country        6 non-null      str
 3   Country Code      6 non-null      str
 4   Founded Year      6 non-null      int64
 5   Fleet Size        6 non-null      int64
 6   Max TEU Capacity  6 non-null      int64
 7   Credit Rating     6 non-null      str
 8   Contact Email     6 non-null      str
 9   Avg Rating (1-5)  6 non-null      float64
 10  Status            6 non-null      str
dtypes: float64(1), int64(3), str(7)
memory usage: 954.0 bytes

In [22]:
ports.info()

<class 'pandas.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 7 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   port_id              7 non-null      str
 1   port_name            7 non-null      str
 2   city                 7 non-null      str
 3   country_code         7 non-null      str
 4   country_full         7 non-null      str
 5   port_type            7 non-null      str
 6   annual_capacity_teu  7 non-null      str
dtypes: str(7)
memory usage: 986.0 bytes

In [23]:
# Generate statistical summary for numerical columns.

shipments.describe()

,transit_duration_hours,shipment_value_usd,temperature_celsius,humidity_percent,delay_duration_hours,delay_penalty_rate_usd_per_hr,total_delay_penalty_usd
count,358990.000000,358990.000000,358990.000000,358990.000000,358990.000000,358990.000000,358990.000000
mean,324.649694,71086.383982,17.554726,61.416493,14.972484,6.472911,263.279977
std,191.643249,58342.120571,18.598191,16.441329,32.661717,8.903652,595.387626
min,48.000000,2423.520000,-25.000000,30.000000,0.000000,0.000000,0.000000
25%,157.000000,29572.260000,9.680000,47.300000,0.000000,0.000000,0.000000
50%,283.200000,51989.925000,23.180000,63.610000,0.000000,0.000000,0.000000
75%,483.975000,94609.085000,31.560000,75.250000,16.050000,14.920000,265.357500
max,719.900000,500000.000000,41.980000,89.980000,400.000000,27.460000,10506.240000

In [25]:
# Check for missing values in each dataset.

shipments.isnull().sum()

movement_id                           0
shipment_id                           0
container_id                          0
customer_id                           0
carrier_name                          0
origin_port                           0
origin_city                           0
origin_country                        0
destination_port                      0
destination_city                      0
destination_country                   0
departure_timestamp                   0
expected_arrival_timestamp            0
actual_arrival_timestamp         241296
transit_duration_hours                0
status                                0
container_type                        0
cargo_type                            0
shipment_value_usd                    0
temperature_celsius                   0
humidity_percent                      0
delay_duration_hours                  0
delay_penalty_rate_usd_per_hr         0
total_delay_penalty_usd               0
is_damaged                            0
late_arrival_flag                     0
dtype: int64

In [26]:
customers.isnull().sum()

customer_id          0
company_name         0
country              0
phone                0
email                0
registration_year    0
credit_tier          0
dtype: int64

In [27]:
carriers.isnull().sum()

Carrier ID          0
Carrier Name        0
HQ Country          0
Country Code        0
Founded Year        0
Fleet Size          0
Max TEU Capacity    0
Credit Rating       0
Contact Email       0
Avg Rating (1-5)    0
Status              0
dtype: int64

In [28]:
ports.isnull().sum()

port_id                0
port_name              0
city                   0
country_code           0
country_full           0
port_type              0
annual_capacity_teu    0
dtype: int64

In [29]:
# Check for duplicate records in each dataset.

shipments.duplicated().sum()

np.int64(0)

In [30]:
customers.duplicated().sum()

np.int64(0)

In [31]:
carriers.duplicated().sum()

np.int64(0)

In [32]:
ports.duplicated().sum()

np.int64(0)

In [33]:
# Export the statistical summary for future reference (Optional).

shipments.describe().to_csv("shipment_summary.csv")