In [1]:
# Import the required libraries.

import pandas as pd
import numpy as np

In [2]:
# Load all project datasets.

shipments = pd.read_csv("../Dataset/shipments.csv")
customers = pd.read_csv("../Dataset/customers.csv")
carriers = pd.read_csv("../Dataset/carriers.csv")
ports = pd.read_csv("../Dataset/ports.csv")

In [3]:
# Display the first 5 records before cleaning.

shipments.head()

,movement_id,shipment_id,container_id,customer_id,carrier_name,origin_port,origin_city,origin_country,destination_port,destination_city,...,container_type,cargo_type,shipment_value_usd,temperature_celsius,humidity_percent,delay_duration_hours,delay_penalty_rate_usd_per_hr,total_delay_penalty_usd,is_damaged,late_arrival_flag
0,MVT300001,SHP400000,CNT200001,CUST0079,Maersk,Port of Los Angeles,Los Angeles,US,Port of Dubai (Jebel Ali),Dubai,...,Reefer,Frozen Food,47709.85,-23.0,81.71,25.25,19.83,500.82,False,True
1,MVT300002,SHP400000,CNT200001,CUST0079,Maersk,Port of Los Angeles,Los Angeles,US,Port of Dubai (Jebel Ali),Dubai,...,Reefer,Frozen Food,58166.39,-23.0,81.71,13.70,22.78,312.09,False,True
2,MVT300004,SHP400000,CNT200001,CUST0079,Maersk,Port of Los Angeles,Los Angeles,US,Port of Dubai (Jebel Ali),Dubai,...,Reefer,Frozen Food,86482.24,-23.0,81.71,40.70,20.93,851.94,False,True
3,MVT300006,SHP400000,CNT200001,CUST0079,Maersk,Port of Los Angeles,Los Angeles,US,Port of Dubai (Jebel Ali),Dubai,...,Reefer,Frozen Food,88148.54,-23.0,81.71,20.85,21.17,441.44,False,True
4,MVT300007,SHP400000,CNT200001,CUST0079,Maersk,Port of Los Angeles,Los Angeles,US,Port of Dubai (Jebel Ali),Dubai,...,Reefer,Frozen Food,41482.11,-23.0,81.71,39.04,22.90,893.92,False,True

In [4]:
# Check the data types of all columns.

shipments.dtypes

movement_id                          str
shipment_id                          str
container_id                         str
customer_id                          str
carrier_name                         str
origin_port                          str
origin_city                          str
origin_country                       str
destination_port                     str
destination_city                     str
destination_country                  str
departure_timestamp                  str
expected_arrival_timestamp           str
actual_arrival_timestamp             str
transit_duration_hours           float64
status                               str
container_type                       str
cargo_type                           str
shipment_value_usd               float64
temperature_celsius              float64
humidity_percent                 float64
delay_duration_hours             float64
delay_penalty_rate_usd_per_hr    float64
total_delay_penalty_usd          float64
is_damaged                          bool
late_arrival_flag                   bool
dtype: object

In [5]:
# Check the total number of missing values in each column.

shipments.isnull().sum()

movement_id                           0
shipment_id                           0
container_id                          0
customer_id                           0
carrier_name                          0
origin_port                           0
origin_city                           0
origin_country                        0
destination_port                      0
destination_city                      0
destination_country                   0
departure_timestamp                   0
expected_arrival_timestamp            0
actual_arrival_timestamp         241296
transit_duration_hours                0
status                                0
container_type                        0
cargo_type                            0
shipment_value_usd                    0
temperature_celsius                   0
humidity_percent                      0
delay_duration_hours                  0
delay_penalty_rate_usd_per_hr         0
total_delay_penalty_usd               0
is_damaged                            0
late_arrival_flag                     0
dtype: int64

In [6]:
# Check the total number of duplicate records.

shipments.duplicated().sum()

np.int64(0)

In [7]:
# Remove duplicate records from the shipments dataset.

shipments = shipments.drop_duplicates()

In [8]:
# Verify that duplicate records have been removed.

shipments.duplicated().sum()

np.int64(0)

In [20]:
# Convert timestamp columns into datetime format.

date_format = "%d-%m-%Y %H:%M"

shipments["departure_timestamp"] = pd.to_datetime(
    shipments["departure_timestamp"],
    format=date_format
)

shipments["expected_arrival_timestamp"] = pd.to_datetime(
    shipments["expected_arrival_timestamp"],
    format=date_format
)

shipments["actual_arrival_timestamp"] = pd.to_datetime(
    shipments["actual_arrival_timestamp"],
    format=date_format,
    errors="coerce"
)

In [21]:
# Verify the updated data types.

shipments.dtypes

movement_id                                 str
shipment_id                                 str
container_id                                str
customer_id                                 str
carrier_name                                str
origin_port                                 str
origin_city                                 str
origin_country                              str
destination_port                            str
destination_city                            str
destination_country                         str
departure_timestamp              datetime64[us]
expected_arrival_timestamp       datetime64[us]
actual_arrival_timestamp         datetime64[us]
transit_duration_hours                  float64
status                                      str
container_type                              str
cargo_type                                  str
shipment_value_usd                      float64
temperature_celsius                     float64
humidity_percent                        float64
delay_duration_hours                    float64
delay_penalty_rate_usd_per_hr           float64
total_delay_penalty_usd                 float64
is_damaged                                 bool
late_arrival_flag                          bool
dtype: object

In [22]:
# Check for missing values again after datatype conversion.

shipments.isnull().sum()

movement_id                           0
shipment_id                           0
container_id                          0
customer_id                           0
carrier_name                          0
origin_port                           0
origin_city                           0
origin_country                        0
destination_port                      0
destination_city                      0
destination_country                   0
departure_timestamp                   0
expected_arrival_timestamp            0
actual_arrival_timestamp         241296
transit_duration_hours                0
status                                0
container_type                        0
cargo_type                            0
shipment_value_usd                    0
temperature_celsius                   0
humidity_percent                      0
delay_duration_hours                  0
delay_penalty_rate_usd_per_hr         0
total_delay_penalty_usd               0
is_damaged                            0
late_arrival_flag                     0
dtype: int64

In [23]:
# Fill missing values in numerical columns with their median.

numeric_columns = shipments.select_dtypes(include=["int64", "float64"]).columns

shipments[numeric_columns] = shipments[numeric_columns].fillna(
    shipments[numeric_columns].median()
)

In [24]:
# Fill missing values in categorical columns with 'Unknown'.

categorical_columns = shipments.select_dtypes(include=["object"]).columns

shipments[categorical_columns] = shipments[categorical_columns].fillna("Unknown")

C:\Users\Nilesh Kamble\AppData\Local\Temp\ipykernel_16424\498060842.py:3: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_columns = shipments.select_dtypes(include=["object"]).columns

In [25]:
# Verify that all missing values have been handled.

shipments.isnull().sum()

movement_id                           0
shipment_id                           0
container_id                          0
customer_id                           0
carrier_name                          0
origin_port                           0
origin_city                           0
origin_country                        0
destination_port                      0
destination_city                      0
destination_country                   0
departure_timestamp                   0
expected_arrival_timestamp            0
actual_arrival_timestamp         241296
transit_duration_hours                0
status                                0
container_type                        0
cargo_type                            0
shipment_value_usd                    0
temperature_celsius                   0
humidity_percent                      0
delay_duration_hours                  0
delay_penalty_rate_usd_per_hr         0
total_delay_penalty_usd               0
is_damaged                            0
late_arrival_flag                     0
dtype: int64

In [26]:
# Standardize text columns by removing extra spaces.

text_columns = shipments.select_dtypes(include=["object"]).columns

for column in text_columns:
    shipments[column] = shipments[column].str.strip()

C:\Users\Nilesh Kamble\AppData\Local\Temp\ipykernel_16424\3247885383.py:3: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  text_columns = shipments.select_dtypes(include=["object"]).columns

In [27]:
# Check the statistical summary after cleaning.

shipments.describe()

,departure_timestamp,expected_arrival_timestamp,actual_arrival_timestamp,transit_duration_hours,shipment_value_usd,temperature_celsius,humidity_percent,delay_duration_hours,delay_penalty_rate_usd_per_hr,total_delay_penalty_usd
count,358990,358990,117694,358990.000000,358990.000000,358990.000000,358990.000000,358990.000000,358990.000000,358990.000000
mean,2023-07-05 06:54:32.972673,2023-07-18 19:33:31.872587,2023-07-14 21:50:53.737148,324.649694,71086.383982,17.554726,61.416493,14.972484,6.472911,263.279977
min,2022-01-01 00:04:00,2022-01-06 04:08:00,2022-01-06 01:16:00,48.000000,2423.520000,-25.000000,30.000000,0.000000,0.000000,0.000000
25%,2022-09-30 22:43:00,2022-10-15 09:07:00,2022-10-09 11:48:00,157.000000,29572.260000,9.680000,47.300000,0.000000,0.000000,0.000000
50%,2023-07-04 22:27:30,2023-07-19 16:01:00,2023-07-15 15:29:00,283.200000,51989.925000,23.180000,63.610000,0.000000,0.000000,0.000000
75%,2024-04-06 04:03:00,2024-04-18 22:01:00,2024-04-22 08:17:00,483.975000,94609.085000,31.560000,75.250000,16.050000,14.920000,265.357500
max,2024-12-30 22:42:00,2025-01-28 21:13:00,2025-01-29 23:28:00,719.900000,500000.000000,41.980000,89.980000,400.000000,27.460000,10506.240000
std,NaN,NaN,NaN,191.643249,58342.120571,18.598191,16.441329,32.661717,8.903652,595.387626

In [28]:
# Save the cleaned shipments dataset.

shipments.to_csv("../Dataset/cleaned_shipments.csv", index=False)